version: "3.9"

services:
  db:
    image: postgres:15
    container_name: jenkins_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saksham123
      POSTGRES_DB: jenkins_ai_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  backend:
    image: saks04/jenkins-ai-backend:latest
    container_name: jenkins_ai_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:saksham123@db:5432/jenkins_ai_database
      ENV: production
    ports:
      - "8000:8000"
    volumes:
      - faiss_data:/app/embeddings
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

  frontend:
    image: saks04/jenkins-ai-frontend:latest
    container_name: jenkins_ai_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
  faiss_data:
  hf_cache:
